DROP DATABASE IF EXISTS burger1_db;

CREATE DATABASE burger1_db;
USE burger1_db;

CREATE TABLE burgers
(
id INTEGER AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
devour BOOLEAN DEFAULT false,
PRIMARY KEY (id)
);